require 'rubygems'
require 'erb'
require 'cgi'
#require 'json'
require 'fileutils'
#require 'redcarpet'

require 'syabh-gazette/name_generator.rb'
require 'syabh-gazette/island_parser.rb'
require 'syabh-gazette/island.rb'